import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";

import "bootstrap-icons/font/bootstrap-icons.css";
import Providers from "@/components/ThemeHydration";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <Providers>
          <div className="w-full transition duration-[200ms]">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
